### ISSUE TITLE
Build failed for mac when using github actions

### ISSUE THREAD

**Issue by BebopSpikeSpiegel** [doitian/live2dviewer#7]
I use this as build configuration workflow:
```
name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
#          - StandaloneWindows # Build a Windows standalone.
#          - StandaloneWindows64 # Build a Windows 64-bit standalone.
#          - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - iOS # Build an iOS player.
#          - Android # Build an Android .apk standalone app.
#          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}

```

And it gives me this: [here](https://github.com/BadBoySeventeen/live2dviewer/actions/runs/1256308338)
raw log:[here](https://pipelines.actions.githubusercontent.com/kxwyKBRRG5EoPUWdNSX5MzLtWwfq2W6J1fsdQAHGcRmekCEAmu/_apis/pipelines/1/runs/19/signedlogcontent/3?urlExpires=2021-09-21T06%3A11%3A39.5530477Z&urlSigningMethod=HMACV1&urlSignature=iqU1Rui%2FgyMZMJSAo5gu%2F104s2NiBlQtBN6PXDJbT50%3D)
